# 메트릭 서버(파드의 자원 상황 모니터링 툴) 설치 : Pod의 현 상황을 실시간으로 알려주는 툴
## kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

# Horizontal Pod Autoscaler
# 컨테이너 자동확장
## 10분 지나고 부하가 없을 시 자동으로 기본 POD대수로 돌아옴
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ordersystem-hpa
  namespace: ro
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-system-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

# 부하 테스트 linux 스크립트
## kubectl exec -it 파드명 /bin/bash -n 네임스페이스
## while true; do curl -s http://order-system-servece/product/list; done
### 리눅스 스크립트

# 부하 모니터링
# -w : watch 옵션을 의미
## kubectl get hpa ordersystem-hpa -n ro -w




