# 아래의 주요 key, secret은 쿠버네티스의 secret 자원을 사용하여 실행시점에 대체


server:
  port: 8080

spring:
#  config:
#    activate:
#      on-profile: local

  redis:
    # 아래의 REDIS_HOST는 k8s의 Deployment에서 정의한 env 변수명과 일치해야함
    host: ${REDIS_HOST}
    port: 6379

# rabbitmq 환경설정
#  rabbitmq:
#    host: localhost
#    port: 5672 # rabbitmq 를 생성한 redis의 port
#    username: guest # rabbitmq 의 계정 정보
#    password: guest
#    virtual-host: /

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}/ordersystem
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    # spring에서 db로의 커넥션 개수 제한
    # 기본적으로 대략 10개 가량의 커넥션이 1개의 서버에서 발생. 따라서 해당 제한을 반드시 해줘야한다.
    tomcat:
      max-active: 5
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
logging:
  level:
    root: info
jwt:
  expiration: 30
  secretKey: ${JWT_SECRET} #변수화한 tokenKey 값
  expirationRt: 14400
  secretKeyRt: ${JWT_SECRET_RT} #변수화한 rt 값

# aws s3 설정
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-southeast-2
    s3:
      bucket: jungeun-file


