#한 pod 안에 컨테이너 2개인 경우
apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox-pod
  namespace: ro
  labels:
    app: nginx-busybox-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: busybox # 헬스체크용
      image: busybox
      command: ['sh','-c', 'while true; do wget -qO- http://localhost:80; sleep 5; done']
