# 스크립트에 대한 버전을 명시
apiVersion: v1
# 자원의 종류를 명시
kind: Pod
metadata:
  name: nginx-pod
  namespace: ro #나의 namespace 이름 넣기
  # labels는 service의 라우팅 대상이 되는 이름
  # service의 selector.app을 통해 매핑
  labels:
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

# 스크립트로 만들기
## kubectl apply -f .\nginx_pod.yml
# 지우기
## kubectl delete -f .\nginx_pod.yml
# 확인하기
## kubectl get pod -n ro
# 재생성
## kubectl apply -f .\nginx_pod.yml
# 로그보기
## kubectl logs nginx-pod -n ro