apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  namespace: ro
spec:
  replicas: 2 # 최대 개수
  # 아래 요소는 replicaset이 관리할 파드를 선택하기 위한 이름
  # selector.matchLabels.app은 template.metadata.labels.app 의 이름과 일치해야함!!!
  selector:
    matchLabels:
      app: my-nginx # 일치 1 : 시작
  template:
  # 아래 labels.app 부분은 service의 selector 부분과 일치해야하고
  # 위의 metadata.labels와도 일치해야함
    metadata:
      labels:
        app: my-nginx # 일치 2
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ro
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30105
  selector:
    app: my-nginx # 일치 3 : 완료
  


