apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  namespace: ro
  labels:
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
--- # --- 를 기준으로 한 파일에서 다른 pod라는 것을 구분함
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  namespace: ro
  labels:
    app: my-nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ro
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30105
  selector:
    app: my-nginx
  

